#!/usr/bin/env node

const program = require('commander')
const { download } = require('./src/download')

program
  .option('-l, --lang  <items>', 'Language code ISO639-2, E.g: eng,vie')
  .option('-u, --user [value]', 'OpenSubtitle username')
  .option('-p, --pass  [value]', 'OpenSubtitle password')
  .action(callDownload)

program.on('--help', function () {
  console.log('')
  console.log('Examples:')
  console.log('  $ subtitle-downloader download ~/Downloads -l eng,vie -u user -p password')
  console.log('  $ subtitle-downloader download ~/Downloads -l eng,vie')
})

program.parse(process.argv)

async function callDownload (directory, options) {
  const langs = options.lang ? options.lang.split(',') : ['eng']
  const directories = [directory]
  await download(directories, langs, options.user, options.pass)
}
