#!/usr/bin/env node

const program = require('commander')
const { download } = require('./src/download')

program
  .option('-l, --lang  <items>', 'Language code ISO639-2, E.g: eng,vie')
  .option('-u, --user [value]', 'OpenSubtitle username')
  .option('-p, --pass  [value]', 'OpenSubtitle password')
  .action(callDownload)
  .parse(process.argv)

program.on('--help', function () {
  console.log('')
  console.log('Examples:')
  console.log('  $ subtitle-downloader download ~/Downloads -l eng,vie -u user -p password')
  console.log('  $ subtitle-downloader download ~/Downloads -l eng,vie')
  console.log('  $ subtitle-downloader download -l eng,vie ~/a ~/b ~/c ')
})

async function callDownload (directory, options) {
  try {
    const langs = options.lang ? options.lang.split(',') : ['eng']
    const directories = program.args
    await download(directories, langs, options.user, options.pass)
  } catch (ex) {
    console.error(ex)
    console.log('Something wrong, please try: \n$ subtitle-downloader download --help')
  }
}
