const languages = {
  'alb': 'Albanian',
  'ara': 'Arabic',
  'arm': 'Armenian',
  'baq': 'Basque',
  'ben': 'Bengali',
  'bos': 'Bosnian',
  'bre': 'Breton',
  'bul': 'Bulgarian',
  'bur': 'Burmese',
  'cat': 'Catalan',
  'chi': 'Chinese',
  'hrv': 'Croatian',
  'cze': 'Czech',
  'dan': 'Danish',
  'dut': 'Dutch',
  'eng': 'English',
  'epo': 'Esperanto',
  'est': 'Estonian',
  'fin': 'Finnish',
  'fre': 'French',
  'glg': 'Galician',
  'geo': 'Georgian',
  'ger': 'German',
  'ell': 'Greek',
  'heb': 'Hebrew',
  'hin': 'Hindi',
  'hun': 'Hungarian',
  'ice': 'Icelandic',
  'ind': 'Indonesian',
  'ita': 'Italian',
  'jpn': 'Japanese',
  'kaz': 'Kazakh',
  'khm': 'Khmer',
  'kor': 'Korean',
  'lav': 'Latvian',
  'lit': 'Lithuanian',
  'ltz': 'Luxembourgish',
  'mac': 'Macedonian',
  'may': 'Malay',
  'mal': 'Malayalam',
  'mon': 'Mongolian',
  'nor': 'Norwegian',
  'oci': 'Occitan',
  'per': 'Persian',
  'pol': 'Polish',
  'por': 'Portuguese',
  'pob': 'Brazilian Portuguese',
  'rum': 'Romanian',
  'rus': 'Russian',
  'scc': 'Serbian',
  'sin': 'Sinhalese',
  'slo': 'Slovak',
  'slv': 'Slovenian',
  'spa': 'Spanish',
  'swa': 'Swahili',
  'swe': 'Swedish',
  'syr': 'Syriac',
  'tgl': 'Tagalog',
  'tel': 'Telugu',
  'tha': 'Thai',
  'tur': 'Turkish',
  'ukr': 'Ukrainian',
  'urd': 'Urdu',
  'vie': 'Vietnamese'
};

const lang_os_to_iso = {
  sq = "alb",
  ar = "ara",
  hy = "arm",
  eu = "baq",
  bn = "ben",
  bs = "bos",
  br = "bre",
  bg = "bul",
  my = "bur",
  ca = "cat",
  zh = "chi",
  hr = "hrv",
  cs = "cze",
  da = "dan",
  nl = "dut",
  en = "eng",
  eo = "epo",
  et = "est",
  fi = "fin",
  fr = "fre",
  gl = "glg",
  ka = "geo",
  de = "ger",
  el = "ell",
  he = "heb",
  hi = "hin",
  hu = "hun",
  is = "ice",
  id = "ind",
  it = "ita",
  ja = "jpn",
  kk = "kaz",
  km = "khm",
  ko = "kor",
  lv = "lav",
  lt = "lit",
  lb = "ltz",
  mk = "mac",
  ms = "may",
  ml = "mal",
  mn = "mon",
  no = "nor",
  oc = "oci",
  fa = "per",
  pl = "pol",
  pt = "por",
  po = "pob",
  ro = "rum",
  ru = "rus",
  sr = "scc",
  si = "sin",
  sk = "slo",
  sl = "slv",
  es = "spa",
  sw = "swa",
  sv = "swe",
  tl = "tgl",
  te = "tel",
  th = "tha",
  tr = "tur",
  uk = "ukr",
  ur = "urd",
  vi = "vie"
}

const movieExtensions = [
  'webm', 'avi', 'mp4', 'mkv', 'flv', 'wmv'
]

const subtitleExtensions = [
  'srt', 'sub', 'sbv'
]

module.exports = {
  movieExtensions,
  subtitleExtensions,
  languages,
  lang_os_to_iso
};
